services:
  # ---------------------------------------------------------
  # Laravel PHP Application
  # ---------------------------------------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ohmsite-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - 8ohm-network

  # ---------------------------------------------------------
  # Nginx Web Server
  # ---------------------------------------------------------
  web:
    image: nginx:alpine
    container_name: ohmsite-web
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - 8ohm-network
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohmsite.rule=Host(`ohmsite.localhost`)"
      - "traefik.http.services.ohmsite.loadbalancer.server.port=80"
      - "traefik.docker.network=8ohm-network"

networks:
  8ohm-network:
    external: true
